#!/bin/bash -e

# openssl 4 fix
#patch -Np1 -i qca-2.3.10-openssl4_fixes-1.patch

sed -i 's@cert.pem@certs/ca-bundle.crt@' CMakeLists.txt

cmake -B build                                   \
      -D CMAKE_INSTALL_PREFIX=/usr               \
      -D CMAKE_BUILD_TYPE=Release                \
      -D QT6=ON                                  \
      -D QCA_INSTALL_IN_QT_PREFIX=ON             \
      -D QCA_MAN_INSTALL_DIR=/usr/share/man

cmake --build build
DESTDIR=$1 cmake --install build
