#!/bin/sh -e

# Force UTF-8 locale to avoid encoding issues
export LC_ALL=en_US.UTF-8     

sed -i 's@cert.pem@certs/ca-bundle.crt@' CMakeLists.txt

cmake -B build                                   \
      -D CMAKE_INSTALL_PREFIX=/usr               \
      -D CMAKE_BUILD_TYPE=Release                \
      -D QT6=ON                                  \
      -D QCA_INSTALL_IN_QT_PREFIX=ON             \
      -D QCA_MAN_INSTALL_DIR=/usr/share/man

cmake --build build
DESTDIR=$1 cmake --install build