#!/bin/bash -e

cmake -B build                            \
      -D CMAKE_INSTALL_PREFIX=/usr        \
      -D CMAKE_INSTALL_LIBEXECDIR=libexec \
      -D CMAKE_BUILD_TYPE=Release         \
      -D BUILD_QT5=OFF                    \
      -D BUILD_TESTING=OFF                \
      -W no-dev

cmake --build build
DESTDIR=$1 cmake --install build

install -Dm644 kde.pam "$1"/usr/lib/pam.d/kde
install -Dm644 kde-fingerprint.pam "$1"/usr/lib/pam.d/kde-fingerprint
install -Dm644 kde-smartcard.pam "$1"/usr/lib/pam.d/kde-smartcard
