#!/bin/sh -e

cmake -B build                     \
      -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_BUILD_TYPE=Release  \
      -D PHONON_BUILD_QT5=OFF

cmake --build build
DESTDIR=$1 cmake --install build
