#!/bin/sh -e

cmake -B build                            \
      -D CMAKE_INSTALL_PREFIX=/usr        \
      -D CMAKE_SKIP_INSTALL_RPATH=ON      \
      -D CMAKE_BUILD_TYPE=Release         \
      -D BUILD_TESTING=OFF

cmake --build build
DESTDIR=$1 cmake --install build
