#!/bin/bash -e

cmake -B build \
  -D CMAKE_INSTALL_LIBEXECDIR=lib \
  -D INSTALL_PAM_CONFIGURATION:BOOL=OFF \
  -D DBUS_CONFIG_FILENAME=plasma_org.freedesktop.DisplayManager.conf

cmake --build build
DESTDIR="$1" cmake --install build

install -d $1/usr/lib/pam.d
install -Dm644 plasmalogin $1/usr/lib/pam.d/
install -Dm644 plasmalogin-autologin $1/usr/lib/pam.d/
install -Dm644 plasmalogin-greeter $1/usr/lib/pam.d/
