#!/bin/bash -e

# opencv 5 fix
sed -e 's|OpenCV 4.7|OpenCV 5|' -i CMakeLists.txt

cmake -B build \
  -D CMAKE_INSTALL_LIBEXECDIR=lib \
  -D BUILD_TESTING=OFF

cmake --build build
DESTDIR=$1 cmake --install build
