#!/bin/sh -e

cmake -B build                     \
      -D CMAKE_INSTALL_PREFIX=/usr \
      -D CMAKE_BUILD_TYPE=Release  \
      -D KDSoap_QT6=ON

cmake --build build
DESTDIR=$1 cmake --install build
