#!/bin/sh -e

cmake -B build                    \
  -D CMAKE_INSTALL_LIBEXECDIR=lib \
  -D BUILD_TESTING=OFF

cmake --build build
DESTDIR="${1}" cmake --install build
setcap CAP_NET_RAW=+ep "${1}"/usr/lib/ksysguard/ksgrd_network_helper
