#!/bin/sh -e

cmake -B build                            \
      -D CMAKE_INSTALL_PREFIX=/usr        \
      -D CMAKE_INSTALL_LIBEXECDIR=libexec \
      -D CMAKE_BUILD_TYPE=Release         \
      -D BUILD_QT5=OFF                    \
      -D WITH_PYTHON_VENDORING=OFF        \
      -D BUILD_TESTING=OFF                \
      -W no-dev

cmake --build build
DESTDIR=$1 cmake --install build
