#!/bin/bash -e

cmake -B build                            \
      -D CMAKE_INSTALL_PREFIX=/usr        \
      -D CMAKE_INSTALL_LIBEXECDIR=libexec \
      -D CMAKE_BUILD_TYPE=Release         \
      -D BUILD_QT5=OFF                    \
      -D BUILD_DOC=OFF                    \
      -D BUILD_TESTING=OFF                \
      -W no-dev

cmake --build build
DESTDIR=$1 cmake --install build

install -Dm644 kcm-about-distrorc "$1"/etc/xdg/kcm-about-distrorc
install -Dm644 logo.png "$1"/usr/share/kinfocenter/logo.png
