#!/bin/bash -e

cmake -B build                            \
      -D CMAKE_INSTALL_PREFIX=/usr        \
      -D CMAKE_INSTALL_LIBEXECDIR=libexec \
      -D CMAKE_BUILD_TYPE=Release         \
      -D BUILD_QT5=OFF                    \
      -D BUILD_TESTING=OFF                \
      -W no-dev

cmake --build build
DESTDIR=$1 cmake --install build

# breeze-cursors
_pick "$1" breeze-cursors usr/share/icons/Breeze_Light/cursors/
_pick "$1" breeze-cursors usr/share/icons/breeze_cursors/cursors/
