#!/bin/sh -e

cmake -B build                                                         \
      -D CMAKE_INSTALL_PREFIX=/usr                                     \
      -D CMAKE_INSTALL_LIBEXECDIR=/usr/lib/sddm                        \
      -D BUILD_WITH_QT6=ON                                             \
      -D DBUS_CONFIG_DIR=/usr/share/dbus-1/system.d                    \
      -D DBUS_CONFIG_FILENAME=sddm_org.freedesktop.DisplayManager.conf \
      -D BUILD_MAN_PAGES=ON                                            \
      -D CMAKE_POLICY_VERSION_MINIMUM=3.5                              \
      -D UID_MAX=60513

cmake --build build
DESTDIR="$1" cmake --install build

install -d "$1"/usr/lib/sddm/sddm.conf.d
"$1"/usr/bin/sddm --example-config > "$1"/usr/lib/sddm/sddm.conf.d/default.conf
# Don't set PATH in sddm.conf
sed -r 's|DefaultPath=.*|DefaultPath=/usr/local/sbin:/usr/local/bin:/usr/bin|g' -i "$1"/usr/lib/sddm/sddm.conf.d/default.conf
# Unset InputMethod https://github.com/sddm/sddm/issues/952
sed -e "/^InputMethod/s/qtvirtualkeyboard//" -i "$1"/usr/lib/sddm/sddm.conf.d/default.conf
