#!/bin/sh -e

cmake -B build -G Ninja               \
  -D CMAKE_INSTALL_PREFIX=/usr        \
  -D CMAKE_BUILD_TYPE=Release         \
  -D BUILD_TESTING=OFF                \
  -Wno-dev

cmake --build build
DESTDIR=$1 cmake --install build
