#!/bin/sh -e

cmake -B build                    \
  -D CMAKE_INSTALL_LIBEXECDIR=lib \
  -D QT_MAJOR_VERSION=6           \
  -D BUILD_TESTING=OFF

cmake --build build
DESTDIR="${1}" cmake --install build
