#!/bin/sh -e

cmake -B build                        \
      -D CMAKE_INSTALL_PREFIX=/usr    \
      -D CMAKE_BUILD_TYPE=Release     \
      -D CMAKE_SKIP_INSTALL_RPATH=ON  \
      -D QT_MAJOR_VERSION=6           \
      -W no-dev

cmake --build build
DESTDIR=$1 cmake --install build
