#!/bin/sh -e

cmake -B build                            \
      -D CMAKE_INSTALL_PREFIX=/usr        \
      -D CMAKE_INSTALL_LIBEXECDIR=libexec \
      -D CMAKE_SKIP_INSTALL_RPATH=ON      \
      -D CMAKE_BUILD_TYPE=Release         \
      -D BUILD_TESTING=OFF                \
      -D BUILD_PYTHON_BINDINGS=OFF        \
      -W no-dev

cmake --build build
DESTDIR=$1 cmake --install build
